# Generated by Django 5.0 on 2023-12-24 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="committee",
            old_name="topic_1",
            new_name="topic",
        ),
        migrations.RemoveField(
            model_name="committee",
            name="topic_2",
        ),
    ]
