# Generated by Django 5.0 on 2023-12-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_alter_committee_cochair_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="email",
            field=models.EmailField(
                blank=True, default="@amb.sch.ae", max_length=254, null=True
            ),
        ),
    ]
