# Generated by Django 5.0 on 2024-01-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_alter_board_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="background_guide",
            field=models.FileField(
                default="background_guide/default.pdf",
                max_length=254,
                upload_to="background_guide",
            ),
        ),
    ]
