# Generated by Django 4.1.4 on 2024-02-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_misc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_1',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_1_Break_End',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_1_Break_Start',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_1_Committee_Session_1_End',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_1_Committee_Session_1_Start',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_1_Committee_Session_2_End',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_1_Committee_Session_2_Start',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_1_Opening_Ceremony_End',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_1_Opening_Ceremony_Start',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_1_Registration_End',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_1_Registration_Start',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_2',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_2_Break_End',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_2_Break_Start',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_2_Closing_Ceremony_End',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_2_Closing_Ceremony_Start',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_2_Committee_Session_3_End',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_2_Committee_Session_3_Start',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_2_Committee_Session_4_End',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='MUN_Day_2_Committee_Session_4_Start',
        ),
        migrations.AddField(
            model_name='misc',
            name='Key',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='misc',
            name='Value',
            field=models.CharField(default='', max_length=500000),
        ),
    ]
