# Generated by Django 4.1.4 on 2024-02-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_misc_mun_day_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misc',
            name='id',
        ),
        migrations.AlterField(
            model_name='misc',
            name='Key',
            field=models.CharField(default='', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
