# Generated by Django 4.1.4 on 2024-05-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_misc_id_alter_misc_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.FileField(upload_to='gallery/')),
                ('description', models.CharField(choices=[('none', 'Hidden'), ('block', 'Shown')], default='block', max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='misc',
            name='Key',
            field=models.CharField(default='423751', max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(default='', max_length=10000)),
                ('album_description', models.CharField(default='', max_length=10000)),
                ('cover_photo', models.ImageField(default='album_cover_photos/placeholder.webp', upload_to='album_cover_photos/')),
                ('media_ids', models.ManyToManyField(to='website.mediaitem')),
            ],
        ),
    ]
