# Generated by Django 4.1.4 on 2024-05-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_gallery_album_alter_misc_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='media_ids',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='album',
            field=models.ForeignKey(default='4444444', on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='website.album'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='misc',
            name='Key',
            field=models.CharField(default='43780', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
