# Generated by Django 4.1.4 on 2024-05-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_album_media_ids_mediaitem_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misc',
            name='Key',
            field=models.CharField(default='136328', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
