# Generated by Django 4.1.4 on 2024-05-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_misc_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='description_visibility',
            field=models.CharField(choices=[('none', 'Hidden'), ('block', 'Shown')], default='block', max_length=10000),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='misc',
            name='Key',
            field=models.CharField(default='308222', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
