# Generated by Django 4.1.4 on 2024-05-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_mediaitem_description_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misc',
            name='Key',
            field=models.CharField(default='401158', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
