# Generated by Django 4.1.4 on 2024-05-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_misc_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Photo')], default='image', max_length=70),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='video',
            field=models.URLField(default='https://www.youtube.com/embed/watch?v=dQw4w9WgXcQ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='photo',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='misc',
            name='Key',
            field=models.CharField(default='626981', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
