# Generated by Django 5.0 on 2024-12-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0020_alter_mediaitem_photo_alter_mediaitem_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="club",
        ),
        migrations.AlterField(
            model_name="misc",
            name="Key",
            field=models.CharField(
                default="704682", max_length=1000, primary_key=True, serialize=False
            ),
        ),
    ]
