# Generated by Django 5.0 on 2024-12-30 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0021_remove_board_club_alter_misc_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="committee",
            name="cochair_id",
        ),
        migrations.AddField(
            model_name="committee",
            name="chair_3_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chair_3_committees",
                to="website.chair",
            ),
        ),
        migrations.AlterField(
            model_name="misc",
            name="Key",
            field=models.CharField(
                default="551550", max_length=1000, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="CoChair",
        ),
    ]
