# Generated by Django 5.0.6 on 2024-12-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_committee_cochair_id_committee_chair_3_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_title', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='misc',
            name='Key',
            field=models.CharField(default='762091', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
