# Generated by Django 5.0.6 on 2024-12-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_scheduleentry_alter_misc_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misc',
            name='Key',
            field=models.CharField(default='405776', max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='event_title',
            field=models.CharField(max_length=10000),
        ),
    ]
